### PR TITLE
Features implementation

### PR DESCRIPTION
**Pull request by fernando-silvabr66**
In this pull request I am delivering the features requested by the task assignment as follow:
- Rails  App creation as API.
- Create a table using PostgreSQL Database to store different greeting messages.
- Provide API endpoints that selects a random greeting from the DB table.
- Using a controller with an action to deliver the greeting messages.
- Added rail routes to the API endpoints.
- Testing connections to Frontend.

### CODE REVIEW

**Review by codecaiine — COMMENTED** [review]
Hi @fernando-silvabr66 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has not complete readme and Pull request is not descriptive. Please make sure that your pull request title is descriptive . It should give a hint of what you are doing in your PR . also please make sure that your future features section has 1 - 3 feature key ,yours is empty . :+1: 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mwanawabangona — CHANGES_REQUESTED** [review]
Hi @fernando-silvabr66 ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project,` that In the README file for the front-end, you should add a link to the backend part, as well as document the readme file in the front-end accordingly`.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by fernando-silvabr66** [comment]
Hi @mwanawabangona, ( and also @codecaiine )

Please, enlight me... as I have this in my Backend's README.md file:
image

And in the frontend I have this API's link (as mentioned in the assignments):
image

I could not understand your comment (nor the comment from the previous code reviewer), could you provide me more details on how exactly I should proceed? Thanks in advance.

**Review by mwanawabangona — APPROVED** [review]
Hi @fernando-silvabr66,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  

H
## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
